<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.smartledge</groupId>
        <artifactId>smartledge</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>smartledge-business</artifactId>
    <packaging>pom</packaging>

    <name>smartledge-business</name>
    <description>超级智能体的业务</description>

    <modules>
        <module>smartledge-rag-runtime</module>
        <module>smartledge-knowledge-indexing</module>
        <module>smartledge-knowledge-augmentation</module>
        <module>smartledge-rag-tools-http</module>
        <module>smartledge-model-http</module>
        <module>smartledge-business-chat</module>
    </modules>
</project>
