package org.smartledge.ai.manage.model;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Collections;

/**
 * User-owned metadata attached to one document.  This is deliberately separate from
 * chunk, table, graph and vector metadata, which are generated by the indexing pipeline.
 */
public record DocumentMetadata(Long documentId, Map<String, Object> values, boolean valid) {

    public DocumentMetadata {
        values = values == null
            ? Map.of()
            : Collections.unmodifiableMap(new LinkedHashMap<>(values));
    }

    public static DocumentMetadata invalid(Long documentId) {
        return new DocumentMetadata(documentId, Map.of(), false);
    }
}
