-- 全局系统配置初始快照（schemaVersion=3）。
-- 仅用于全新数据库，或已清空系统配置、配置分类及配置历史数据的本地数据库。
-- 请在 create_table_mysql.sql 建表完成后执行。本脚本可重复执行，已有 id=1 配置不会被覆盖。
-- 本脚本不迁移旧 schema 快照；旧数据必须先由操作者明确清空。
-- 知识库级 retrieval_config_json / graph_rag_config_json / raptor_config_json 只保存差异项，空值自动继承本快照。
-- 总分类和小分类使用独立关系表维护，不写入 config_json，也不改变 schemaVersion。
-- 首次初始化时先执行 create_table_mysql.sql，再执行本脚本写入分类和默认配置。

USE smartledge;
    
START TRANSACTION;

INSERT IGNORE INTO smartledge_system_config_group
    (id, group_key, group_label, group_description, sort_order, create_time, edit_time, status)
VALUES
    (1, 'retrieval', '检索与排序', '控制召回、通道、阈值、融合和执行边界。', 10, NOW(), NOW(), 1),
    (2, 'conversation', '对话与回答', '控制对话助手、RAG 编排和回答上下文。', 20, NOW(), NOW(), 1),
    (3, 'documentBuild', '文档与索引', '控制切块、内容增强、索引和 RAPTOR 构建。', 30, NOW(), NOW(), 1),
    (4, 'graphRag', 'GraphRAG', '控制知识图谱构建和 LLM 受控增强。', 40, NOW(), NOW(), 1),
    (5, 'evaluation', '评测与诊断', '控制评测快照、检索探针和运行诊断。', 50, NOW(), NOW(), 1),
    (6, 'security', '安全与访问', '控制管理员认证和只读预览访问。', 60, NOW(), NOW(), 1);

INSERT IGNORE INTO smartledge_system_config_category
    (id, group_key, category_key, category_label, category_description, sort_order, create_time, edit_time, status)
VALUES
    (101, 'retrieval', 'retrievalWindow', '召回与窗口', '控制各通道召回规模和候选裁剪窗口。', 10, NOW(), NOW(), 1),
    (102, 'retrieval', 'execution', '执行与超时', '控制重排开关和检索等待边界。', 20, NOW(), NOW(), 1),
    (103, 'retrieval', 'relevance', '相关性阈值', '控制低相关候选进入后续阶段的最低要求。', 30, NOW(), NOW(), 1),
    (104, 'retrieval', 'channels', '检索通道', '控制新会话允许调度的检索通道。', 40, NOW(), NOW(), 1),
    (105, 'retrieval', 'fusion', '融合与排序', '控制多通道特征在统一排序窗口中的权重。', 50, NOW(), NOW(), 1),
    (106, 'conversation', 'chatAgent', '对话助手', '控制推荐追问、调用保护、历史轮数和执行超时。', 10, NOW(), NOW(), 1),
    (107, 'conversation', 'ragOrchestration', 'RAG 编排', '控制问题改写、拆问和受控查询计划。', 20, NOW(), NOW(), 1),
    (108, 'conversation', 'ragContext', '上下文与回答', '控制历史、证据预算、长期摘要和回答文案。', 30, NOW(), NOW(), 1),
    (109, 'documentBuild', 'chunking', '切块策略', '控制子块、父块和智能切块的全局默认值。', 10, NOW(), NOW(), 1),
    (110, 'documentBuild', 'chunkEnrichment', '切块内容增强', '控制构建期智能关键词和问题生成。', 20, NOW(), NOW(), 1),
    (111, 'documentBuild', 'indexBuild', '索引构建', '控制向量化批次、并发、重试、刷新和执行器。', 30, NOW(), NOW(), 1),
    (112, 'documentBuild', 'raptorBuild', 'RAPTOR 构建', '控制摘要树规模、模型摘要和质量门槛。', 40, NOW(), NOW(), 1),
    (113, 'graphRag', 'graphRagBuild', 'GraphRAG 构建', '控制构建租约、尝试次数和重试等待。', 10, NOW(), NOW(), 1),
    (114, 'graphRag', 'graphRagEnhancement', 'GraphRAG 增强', '控制受控抽取、社区报告和实体消歧。', 20, NOW(), NOW(), 1),
    (115, 'evaluation', 'evaluationSnapshot', '评测快照', '控制评测快照接口。', 10, NOW(), NOW(), 1),
    (116, 'evaluation', 'retrievalProbe', '检索探针', '控制管理员检索探针。', 20, NOW(), NOW(), 1),
    (117, 'evaluation', 'ragTools', 'RAG 工具服务', '控制 Python rag-tools HTTP 边界。', 30, NOW(), NOW(), 1),
    (118, 'evaluation', 'graphRagDiagnostics', 'GraphRAG 诊断', '控制候选拒绝诊断输出。', 40, NOW(), NOW(), 1),
    (119, 'security', 'adminAuth', '管理员认证', '控制后台认证凭据和令牌有效期。', 10, NOW(), NOW(), 1),
    (120, 'security', 'previewMode', '只读预览', '控制线上只读预览模式。', 20, NOW(), NOW(), 1),
    (121, 'graphRag', 'graphRagExecution', 'GraphRAG 运行保护', '控制 GraphRAG 线程池、预算和拆分。', 30, NOW(), NOW(), 1),
    (122, 'documentBuild', 'chunkEnrichmentExecution', '关键词与问题增强运行保护', '控制关键词与问题增强线程池、并发和预算。', 50, NOW(), NOW(), 1);

INSERT INTO smartledge_system_config
    (id, config_version, config_json, create_time, edit_time, status)
SELECT
    1,
    0,
    JSON_OBJECT(
        'schemaVersion', 3,
        'values', JSON_OBJECT(
            'mvcAsync.corePoolSize', 4,
            'mvcAsync.maxPoolSize', 16,
            'mvcAsync.queueCapacity', 64,
            'mvcAsync.keepAliveSeconds', 60,
            'mvcAsync.shutdownAwaitSeconds', 10,
            'ragRuntime.vectorTopK', 10,
            'ragRuntime.keywordTopK', 10,
            'ragRuntime.graphRagTopK', 5,
            'ragRuntime.graphRagMaxHops', 2,
            'ragRuntime.raptorTopK', 5,
            'ragRuntime.raptorSourceChunkTopK', 3,
            'ragRuntime.candidateTopK', 40,
            'ragRuntime.rerankCandidateTopK', 24,
            'ragRuntime.finalTopK', 6,
            'ragRuntime.rerankEnabled', TRUE,
            'ragRuntime.channelTimeoutMs', 25000,
            'ragRuntime.subQuestionTimeoutMs', 40000,
            'ragRuntime.minVectorSimilarity', 0.45,
            'ragRuntime.keywordRelativeScoreFloor', 0.35,
            'ragRuntime.keywordChannelEnabled', TRUE,
            'ragRuntime.tableChannelEnabled', TRUE,
            'ragRuntime.graphRagChannelEnabled', TRUE,
            'ragRuntime.raptorChannelEnabled', TRUE,
            'ragRuntime.hybrid.vectorWeight', 1,
            'ragRuntime.hybrid.keywordWeight', 1,
            'ragRuntime.hybrid.tableWeight', 1.2,
            'ragRuntime.hybrid.graphRagWeight', 1.1,
            'ragRuntime.hybrid.raptorWeight', 1.05,
            'ragRuntime.hybrid.rankWeight', 1,
            'ragRuntime.hybrid.originalScoreWeight', 0.08,
            'ragRuntime.hybrid.metadataBoostWeight', 0.04,
            'ragRuntime.hybrid.maxMetadataBoost', 1,
            'chat.recommendationEnabled', TRUE,
            'chat.maxModelCallsPerRun', 8,
            'chat.maxModelCallsPerThread', 40,
            'chat.maxToolCallsPerRun', 6,
            'chat.maxToolCallsPerThread', 30,
            'chat.historyPreviewTurns', 4,
            'chat.recommendationTimeoutMs', 3000,
            'rag.enabled', TRUE,
            'rag.rewriteEnabled', TRUE,
            'rag.rewriteHistoryTurns', 4,
            'rag.rewriteOptions.enabled', TRUE,
            'rag.rewriteOptions.temperature', 0.2,
            'rag.rewriteOptions.topP', 0.3,
            'rag.rewriteOptions.thinking', FALSE,
            'rag.maxSubQuestions', 4,
            'rag.graphRagQueryPlanEnabled', TRUE,
            'rag.autoRouteRecommendationThreshold', 0.55,
            'rag.parentEvidenceMaxChars', 2200,
            'rag.planningHistoryMaxChars', 1600,
            'rag.answerHistoryMaxChars', 1000,
            'rag.totalEvidenceMaxChars', 5200,
            'rag.perSubQuestionEvidenceMaxChars', 2200,
            'rag.noEvidenceReply', '当前没有从当前文档中检索到足够证据，暂时不能给出可靠结论。你可以补充更具体的章节名、标题或关键词后再试。',
            'rag.historySummary.enabled', TRUE,
            'rag.historySummary.keepRecentTurns', 4,
            'rag.historySummary.compressionBatchTurns', 6,
            'rag.historySummary.recentTranscriptMaxChars', 2200,
            'rag.historySummary.summaryMaxChars', 1400,
            'rag.raptorMaxClusterSize', 6,
            'rag.raptorMaxLevels', 3,
            'rag.raptorLlmSummaryEnabled', TRUE,
            'rag.raptorSummaryQualityFloor', 0.42,
            'raptor.execution.llmConcurrency', 3,
            'graphRag.build.leaseEnabled', TRUE,
            'graphRag.build.leaseTtlSeconds', 6000,
            'graphRag.build.maxAttempts', 2,
            'graphRag.build.retryBackoffMillis', 500,
            'graphRag.extraction.batchChunkLimit', 1,
            'graphRag.extraction.inputTokenBudget', 4600,
            'graphRag.model.modelContextTokens', 16384,
            'graphRag.model.outputReserve', 4096,
            'graphRag.model.promptReserve', 1024,
            'graphRag.model.modelResponseMaxBytes', 1048576,
            'graphRag.extraction.maxEntityNameChars', 500,
            'graphRag.execution.maxDocumentBytes', 4000000,
            'graphRag.extraction.maxQuoteChars', 180,
            'graphRag.extraction.maxReasonChars', 240,
            'graphRag.extraction.maxUnitTextChars', 420,
            'graphRag.communityReport.enabled', TRUE,
            'adminAuth.tokenExpireMinutes', 720,
            'previewMode.enabled', FALSE,
            'previewMode.message', '线上环境为只读展示模式，仅开放浏览与检索能力',
            'evaluation.snapshot.enabled', TRUE,
            'evaluation.snapshot.maxBatchSize', 20,
            'evaluation.snapshot.requestsPerMinute', 30,
            'evaluation.snapshot.promptVersion', 'prompt-v1',
            'evaluation.retrievalProbe.enabled', FALSE,
            'evaluation.retrievalProbe.requestsPerMinute', 10,
            'evaluation.retrievalProbe.maxQueryLength', 2000,
            'evaluation.retrievalProbe.maxResultCount', 100,
            'ragTools.baseUrl', 'http://127.0.0.1:18080',
            'ragTools.connectTimeoutMs', 3000,
            'ragTools.documentParseReadTimeoutMs', 600000,
            'ragTools.graphExtractReadTimeoutMs', 110000,
            'ragTools.graphExtractionResponseMaxBytes', 16777216,
            'ragTools.raptorBuildReadTimeoutMs', 600000,
            'graphRag.diagnostics.enabled', TRUE,
            'graphRag.diagnostics.directory', 'logs/graph-rag-diagnostics',
            'graphRag.diagnostics.maxTextChars', 4096,
            'graphRag.diagnostics.maxFileBytes', 2097152,
            'graphRag.diagnostics.maxFiles', 20,
            'graphRag.execution.workerThreads', 6,
            'graphRag.execution.queueCapacity', 12,
            'graphRag.execution.documentConcurrency', 6,
            'graphRag.execution.maxBatchAttempts', 3,
            'graphRag.execution.retryBackoffMillis', 1000,
            'graphRag.execution.documentBudgetMillis', 1200000,
            'graphRag.execution.toolBudgetMillis', 100000,
            'graphRag.execution.reserveMillis', 9000,
            'graphRag.execution.maxSplitDepth', 3,
            'graphRag.execution.maxSplits', 32,
            'graphRag.execution.maxTimeoutSplitsPerSource', 2,
            'graphRag.execution.maxBatches', 1024,
            'graphRag.execution.maxCandidateBytes', 16777216,
            'graphRag.execution.maxObservationBytes', 32768,
            'chunkEnrichment.execution.workerThreads', 6,
            'chunkEnrichment.execution.queueCapacity', 12,
            'chunkEnrichment.execution.documentConcurrency', 6,
            'chunkEnrichment.execution.batchTimeoutMillis', 200000,
            'chunkEnrichment.execution.documentBudgetMillis', 660000,
            'chunkEnrichment.execution.pollMillis', 90,
            'graphRag.entityResolution.enabled', TRUE,
            'chunkEnrichment.enabled', TRUE,
            'chunkEnrichment.maxKeywords', 8,
            'chunkEnrichment.maxQuestions', 4,
            'chunkEnrichment.maxKeywordChars', 32,
            'chunkEnrichment.maxQuestionChars', 40,
            'chunkEnrichment.batchChunkLimit', 6,
            'chunkEnrichment.batchTokenLimit', 2400,
            'indexBuild.embeddingBatchSize', 5,
            'indexBuild.embeddingParallelism', 1,
            'indexBuild.embeddingBatchMaxAttempts', 3,
            'indexBuild.embeddingBatchRetryBackoffMillis', 1200,
            'indexBuild.elasticsearchRefreshWait', TRUE,
            'indexBuild.progressLogLimit', 60,
            'indexBuild.executorPoolSize', 2,
            'indexBuild.executorQueueCapacity', 32,
            'chunk.recursiveMaxChars', 800,
            'chunk.recursiveOverlapChars', 120,
            'chunk.semanticMaxChars', 700,
            'chunk.semanticMinChars', 240,
            'chunk.semanticSimilarityThreshold', 0.18,
            'chunk.parentBlockMaxChars', 2200,
            'chunk.parentBlockOverlapChars', 180,
            'chunk.parentSemanticMaxChars', 1600,
            'chunk.parentSemanticMinChars', 480,
            'chunk.llmEnabled', TRUE,
            'chunk.llmMaxChars', 3500,
            'chunk.recommendLlmWhenLowQuality', TRUE
        )
    ),
    NOW(),
    NOW(),
    1
WHERE NOT EXISTS (
    SELECT 1
    FROM smartledge_system_config
    WHERE id = 1
);

COMMIT;
