USE smartledge;
    
CREATE TABLE IF NOT EXISTS smartledge_chat_dialogue (
                                                         id BIGINT NOT NULL COMMENT '主键id',
                                                         dialogue_code VARCHAR(64) NOT NULL COMMENT '业务会话编号',
    dialogue_stage TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1:空闲 2:进行中',
    chat_mode TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1:当前文档问答 2:开放式提问',
    selected_document_id BIGINT DEFAULT NULL COMMENT '当前会话显式锁定的提问文档id',
    selected_document_name VARCHAR(255) DEFAULT NULL COMMENT '当前会话显式锁定的提问文档名称',
    knowledge_base_selection_mode VARCHAR(16) NOT NULL DEFAULT 'NONE' COMMENT '当前会话知识库选择模式 NONE/ALL/SELECTED',
    selected_knowledge_base_ids_json JSON DEFAULT NULL COMMENT '当前会话已选知识库id快照',
    selected_knowledge_base_names_json JSON DEFAULT NULL COMMENT '当前会话已选知识库名称快照',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_smartledge_chat_dialogue_code_status (dialogue_code, status),
    KEY idx_smartledge_chat_dialogue_stage_status (dialogue_stage, status),
    KEY idx_smartledge_chat_dialogue_edit_time (edit_time)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务对话归档主表';

CREATE TABLE IF NOT EXISTS smartledge_chat_exchange (
                                                         id BIGINT NOT NULL COMMENT '主键id',
                                                         dialogue_code VARCHAR(64) NOT NULL COMMENT '所属业务会话编号',
    user_prompt TEXT NOT NULL COMMENT '用户提问',
    reply_content LONGTEXT NOT NULL COMMENT '助手回答内容',
    reasoning_note_list JSON NOT NULL COMMENT '过程提示与思考片段',
    source_snapshot_list JSON NOT NULL COMMENT '引用来源快照',
    followup_suggestion_list JSON NOT NULL COMMENT '推荐追问快照',
    tool_trace_list JSON NOT NULL COMMENT '工具使用轨迹快照',
    debug_trace_json JSON DEFAULT NULL COMMENT '调试轨迹快照',
    exchange_state TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1:进行中 2:已完成 3:失败 4:已停止',
    finish_note TEXT DEFAULT NULL COMMENT '失败或终止说明',
    first_token_latency_ms BIGINT DEFAULT NULL COMMENT '首包耗时，毫秒',
    total_latency_ms BIGINT DEFAULT NULL COMMENT '总耗时，毫秒',
    knowledge_base_selection_mode VARCHAR(16) NOT NULL DEFAULT 'NONE' COMMENT '当轮知识库选择模式 NONE/ALL/SELECTED',
    selected_knowledge_base_ids_json JSON DEFAULT NULL COMMENT '当轮已选知识库id快照',
    selected_knowledge_base_names_json JSON DEFAULT NULL COMMENT '当轮已选知识库名称快照',
    retrieval_config_snapshot_json JSON DEFAULT NULL COMMENT '当轮生效RAG检索配置快照',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_smartledge_chat_exchange_dialogue_status (dialogue_code, status),
    KEY idx_smartledge_chat_exchange_state_status (exchange_state, status),
    KEY idx_smartledge_chat_exchange_create_time (create_time)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务对话轮次归档表';

CREATE TABLE IF NOT EXISTS smartledge_chat_memory_summary (
                                                               id BIGINT NOT NULL COMMENT '主键id',
                                                               dialogue_code VARCHAR(64) NOT NULL COMMENT '所属业务会话编号',
    covered_exchange_id BIGINT NOT NULL DEFAULT '0' COMMENT '长期摘要已覆盖到的最后一条exchangeId',
    covered_exchange_count INT NOT NULL DEFAULT '0' COMMENT '长期摘要已覆盖的轮次数',
    compression_count INT NOT NULL DEFAULT '0' COMMENT '累计压缩次数',
    summary_version INT NOT NULL DEFAULT '0' COMMENT '摘要版本号',
    summary_text LONGTEXT NOT NULL COMMENT '编排阶段直接使用的长期摘要文本',
    summary_json JSON DEFAULT NULL COMMENT '长期摘要结构化JSON',
    last_source_edit_time DATETIME DEFAULT NULL COMMENT '摘要覆盖源轮次的最后更新时间',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_smartledge_chat_memory_summary_dialogue (dialogue_code),
    KEY idx_smartledge_chat_memory_summary_cover (covered_exchange_id),
    KEY idx_smartledge_chat_memory_summary_edit_time (edit_time)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务对话长期记忆摘要快照表';

CREATE TABLE IF NOT EXISTS smartledge_chat_exchange_feedback (
                                                                id BIGINT NOT NULL COMMENT '主键id',
                                                                dialogue_code VARCHAR(64) NOT NULL COMMENT '所属业务会话编号',
    exchange_id BIGINT NOT NULL COMMENT '被评价的轮次id（复用 smartledge_chat_exchange.id）',
    user_id BIGINT NOT NULL COMMENT '评价用户id（与会话归属一致）',
    tenant_id BIGINT NOT NULL DEFAULT '1' COMMENT '所属租户id',
    rating TINYINT NOT NULL COMMENT '评价 1:有帮助 -1:没有帮助',
    comment VARCHAR(500) DEFAULT NULL COMMENT '可选补充说明',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_smartledge_chat_exchange_feedback_user (exchange_id, user_id),
    KEY idx_smartledge_chat_exchange_feedback_dialogue (dialogue_code),
    KEY idx_smartledge_chat_exchange_feedback_tenant (tenant_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务对话轮次用户反馈表（质量回路的线上数据入口）';

CREATE TABLE IF NOT EXISTS smartledge_long_term_memory (
    id                      BIGINT       NOT NULL COMMENT '主键id',
    tenant_id               BIGINT       NOT NULL DEFAULT '1' COMMENT '所属租户id',
    dialogue_code           VARCHAR(64)  NOT NULL COMMENT '所属业务会话编号',
    user_id                 BIGINT       DEFAULT NULL COMMENT '写入时的用户id，可空',
    entity_key              VARCHAR(80)  NOT NULL COMMENT '事实实体键',
    fact_text               VARCHAR(512) NOT NULL COMMENT '事实文本',
    source_kind             VARCHAR(32)  NOT NULL COMMENT 'USER_EXPLICIT / MODEL_CANDIDATE',
    lifecycle               VARCHAR(32)  NOT NULL COMMENT 'ACTIVE / SUPERSEDED / REJECTED',
    provenance_exchange_id  BIGINT       NOT NULL DEFAULT '0' COMMENT '写入来源轮次',
    version                 INT          NOT NULL DEFAULT '1' COMMENT '同键版本，从 1 递增',
    create_time             DATETIME     DEFAULT NULL COMMENT '创建时间',
    edit_time               DATETIME     DEFAULT NULL COMMENT '编辑时间',
    status                  TINYINT(1)   NOT NULL DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_ltm_conversation_lifecycle (dialogue_code, lifecycle, status),
    KEY idx_ltm_conversation_entity (dialogue_code, entity_key, version)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会话级可寻址长期事实';

CREATE TABLE IF NOT EXISTS smartledge_chat_exchange_trace_stage (
                                                                     id BIGINT NOT NULL COMMENT '主键id',
                                                                     dialogue_code VARCHAR(64) NOT NULL COMMENT '所属业务会话编号',
    exchange_id BIGINT NOT NULL COMMENT '所属轮次id',
    trace_id VARCHAR(64) NOT NULL COMMENT '本轮执行trace id',
    stage_code VARCHAR(64) NOT NULL COMMENT '阶段编码',
    stage_name VARCHAR(128) NOT NULL COMMENT '阶段名称',
    stage_order INT NOT NULL DEFAULT '0' COMMENT '阶段顺序',
    stage_level TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1:一级阶段 2:二级子步骤',
    parent_stage_id BIGINT DEFAULT NULL COMMENT '父阶段id',
    execution_mode VARCHAR(32) DEFAULT NULL COMMENT '执行模式',
    stage_state TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1:运行中 2:完成 3:失败 4:跳过',
    start_time DATETIME DEFAULT NULL COMMENT '阶段开始时间',
    end_time DATETIME DEFAULT NULL COMMENT '阶段结束时间',
    duration_ms BIGINT DEFAULT NULL COMMENT '阶段耗时，毫秒',
    summary_text VARCHAR(1000) DEFAULT NULL COMMENT '阶段摘要',
    error_message TEXT DEFAULT NULL COMMENT '阶段错误信息',
    snapshot_json JSON DEFAULT NULL COMMENT '阶段结构化快照',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_smartledge_chat_trace_exchange (exchange_id, stage_order),
    KEY idx_smartledge_chat_trace_dialogue (dialogue_code, exchange_id),
    KEY idx_smartledge_chat_trace_trace_id (trace_id),
    KEY idx_smartledge_chat_trace_stage_code (stage_code)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='对话轮次执行阶段轨迹表';

-- 自主 Agent 状态与逻辑 checkpoint；应用启动不自动建表。
CREATE TABLE IF NOT EXISTS smartledge_state (
    conversation_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
    exchange_id BIGINT NOT NULL DEFAULT 0,
    active_exchange_id BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    checkpoint_count BIGINT NOT NULL DEFAULT 0,
    model_calls INT NOT NULL DEFAULT 0,
    tool_calls INT NOT NULL DEFAULT 0,
    messages_json JSON NOT NULL DEFAULT (JSON_ARRAY())
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS smartledge_checkpoint (
    conversation_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    checkpoint_no BIGINT NOT NULL,
    exchange_id BIGINT NOT NULL,
    state_version BIGINT NOT NULL,
    PRIMARY KEY (conversation_id, checkpoint_no),
    CONSTRAINT fk_agent_checkpoint_state FOREIGN KEY (conversation_id) REFERENCES smartledge_state(conversation_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `smartledge_knowledge_base` (
                                                            `id` bigint NOT NULL COMMENT '主键id',
                                                            `base_name` varchar(128) NOT NULL COMMENT '知识库名称',
    `description` varchar(1024) DEFAULT NULL COMMENT '知识库描述',
    `retrieval_config_json` JSON DEFAULT NULL COMMENT '检索配置JSON',
    `graph_rag_config_json` JSON DEFAULT NULL COMMENT 'GraphRAG配置JSON',
    `raptor_config_json` JSON DEFAULT NULL COMMENT 'RAPTOR配置JSON',
    `metadata_filter_json` JSON DEFAULT NULL COMMENT '元数据过滤配置JSON',
    `is_default` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否默认知识库 1:是 0:否',
    `sort_order` int DEFAULT '0' COMMENT '排序值',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_knowledge_base_default` (`is_default`, `status`),
    KEY `idx_knowledge_base_sort` (`sort_order`, `id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='轻量知识库表';


CREATE TABLE IF NOT EXISTS `smartledge_document` (
                                                      `id` bigint NOT NULL COMMENT '主键id',
                                                      `document_name` varchar(255) NOT NULL COMMENT '文档名称',
    `original_file_name` varchar(255) NOT NULL COMMENT '原始文件名',
    `file_type` tinyint NOT NULL COMMENT '文件类型 1:PDF 2:DOC 3:DOCX 4:TXT 5:MD 6:HTML 7:XLSX',
    `mime_type` varchar(128) DEFAULT NULL COMMENT 'MIME类型',
    `file_size` bigint DEFAULT '0' COMMENT '文件大小(byte)',
    `storage_type` tinyint NOT NULL DEFAULT '1' COMMENT '存储类型 1:MinIO',
    `bucket_name` varchar(128) DEFAULT NULL COMMENT 'bucket名称',
    `object_name` varchar(512) DEFAULT NULL COMMENT '对象名称',
    `object_url` varchar(1024) DEFAULT NULL COMMENT '文件访问地址',
    `parse_status` tinyint NOT NULL DEFAULT '1' COMMENT '解析状态 1:待解析 2:解析中 3:解析成功 4:解析失败',
    `strategy_status` tinyint NOT NULL DEFAULT '1' COMMENT '策略状态 1:待推荐 2:已推荐 3:已确认 4:已失效',
    `index_status` tinyint NOT NULL DEFAULT '1' COMMENT '索引状态 1:待构建 2:构建中 3:构建成功 4:构建失败',
    `char_count` int DEFAULT '0' COMMENT '解析后字符数',
    `token_count` int DEFAULT '0' COMMENT '解析后token估算数',
    `structure_level` tinyint DEFAULT '0' COMMENT '结构化程度 0:未知 1:低 2:中 3:高',
    `content_quality_level` tinyint DEFAULT '0' COMMENT '内容质量 0:未知 1:低 2:中 3:高',
    `parse_text_path` varchar(512) DEFAULT NULL COMMENT '解析文本存储路径',
    `parse_error_msg` varchar(1000) DEFAULT NULL COMMENT '解析失败原因',
    `knowledge_base_id` bigint NOT NULL COMMENT '所属知识库id',
    `knowledge_base_name` varchar(128) NOT NULL COMMENT '所属知识库名称快照',
    `metadata_json` JSON DEFAULT NULL COMMENT '文档级用户元数据JSON；不含chunk/表格/向量系统元数据',
    `content_hash` varchar(128) DEFAULT NULL COMMENT '文件内容SHA-256',
    `source_uri` varchar(1024) DEFAULT NULL COMMENT '来源URI，默认 MinIO object url',
    `language` varchar(16) DEFAULT NULL COMMENT '文档语言',
    `effective_from` datetime DEFAULT NULL COMMENT '生效起点',
    `expires_at` datetime DEFAULT NULL COMMENT '过期时间，空表示不过期',
    `current_plan_id` bigint DEFAULT NULL COMMENT '当前策略方案id',
    `last_parse_task_id` bigint DEFAULT NULL COMMENT '最近一次成功解析任务id',
    `structure_node_count` int DEFAULT '0' COMMENT '最近一次结构化解析生成的节点数',
    `last_index_task_id` bigint DEFAULT NULL COMMENT '最近一次索引任务id',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_object_name` (`object_name`),
    KEY `idx_parse_status` (`parse_status`),
    KEY `idx_strategy_status` (`strategy_status`),
    KEY `idx_index_status` (`index_status`),
    KEY `idx_knowledge_base_id` (`knowledge_base_id`),
    KEY `idx_kb_content_hash` (`knowledge_base_id`, `content_hash`),
    KEY `idx_expires_at` (`expires_at`),
    KEY `idx_current_plan_id` (`current_plan_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档表';


CREATE TABLE IF NOT EXISTS `smartledge_document_strategy_plan` (
                                                                    `id` bigint NOT NULL COMMENT '主键id',
                                                                    `document_id` bigint NOT NULL COMMENT '文档id',
                                                                    `plan_version` int NOT NULL DEFAULT '1' COMMENT '方案版本号',
                                                                    `plan_source` tinyint NOT NULL DEFAULT '1' COMMENT '方案来源 1:系统推荐 2:用户调整',
                                                                    `plan_status` tinyint NOT NULL DEFAULT '1' COMMENT '方案状态 1:待确认 2:已确认 3:已执行 4:已废弃',
                                                                    `strategy_count` tinyint NOT NULL DEFAULT '0' COMMENT '策略数量',
                                                                    `strategy_snapshot` varchar(255) DEFAULT NULL COMMENT '策略快照，例:1,2,3',
    `chunking_contract_json` longtext COMMENT '文档切块画像合同及来源/规则快照JSON',
    `recommend_reason` text COMMENT '推荐原因',
    `adjust_note` varchar(500) DEFAULT NULL COMMENT '调整说明',
    `confirm_user_id` bigint DEFAULT NULL COMMENT '确认人id',
    `confirm_time` datetime DEFAULT NULL COMMENT '确认时间',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_document_version` (`document_id`, `plan_version`),
    KEY `idx_plan_status` (`plan_status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档策略方案表';


CREATE TABLE IF NOT EXISTS `smartledge_document_strategy_step` (
                                                                    `id` bigint NOT NULL COMMENT '主键id',
                                                                    `plan_id` bigint NOT NULL COMMENT '方案id',
                                                                    `document_id` bigint NOT NULL COMMENT '文档id',
                                                                    `step_no` int NOT NULL COMMENT '执行顺序',
                                                                    `pipeline_type` varchar(16) NOT NULL COMMENT '流水线类型 PARENT:父块流水线 CHILD:子块流水线',
    `strategy_type` tinyint NOT NULL COMMENT '策略类型 1:基于文档结构切块 2:递归分块 3:语义分块 4:大模型智能切块',
    `strategy_role` tinyint NOT NULL DEFAULT '1' COMMENT '策略角色 1:主策略 2:优化策略 3:兜底策略 4:增强策略',
    `source_type` tinyint NOT NULL DEFAULT '1' COMMENT '来源类型 1:系统推荐 2:用户新增 3:用户保留',
    `execute_status` tinyint NOT NULL DEFAULT '1' COMMENT '执行状态 1:待执行 2:执行中 3:执行成功 4:执行失败 5:已跳过',
    `recommend_reason` varchar(500) DEFAULT NULL COMMENT '本步骤推荐原因',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_plan_pipeline_step_no` (`plan_id`, `pipeline_type`, `step_no`),
    KEY `idx_document_id` (`document_id`),
    KEY `idx_strategy_type` (`strategy_type`),
    KEY `idx_pipeline_type` (`pipeline_type`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档策略步骤表';


CREATE TABLE IF NOT EXISTS `smartledge_document_task` (
                                                           `id` bigint NOT NULL COMMENT '主键id',
                                                           `document_id` bigint NOT NULL COMMENT '文档id',
                                                           `plan_id` bigint DEFAULT NULL COMMENT '执行方案id',
                                                           `source_parse_task_id` bigint DEFAULT NULL COMMENT '构建索引任务冻结的源解析任务id；解析任务为空',
                                                           `task_type` tinyint NOT NULL COMMENT '任务类型 1:解析路由 2:构建索引',
                                                           `task_status` tinyint NOT NULL DEFAULT '1' COMMENT '任务状态 1:新建 2:进行中 3:成功 4:失败 5:已取消',
                                                           `current_stage` tinyint NOT NULL DEFAULT '1' COMMENT '当前阶段 1:文件上传 2:内容解析 3:策略路由 4:策略确认 5:切块执行 6:切块后处理 7:向量化 8:入库完成',
                                                           `trigger_source` tinyint NOT NULL DEFAULT '1' COMMENT '触发来源 1:系统自动 2:用户手动',
                                                           `strategy_snapshot` varchar(255) DEFAULT NULL COMMENT '执行时策略快照，例:1,2,3',
    `retry_count` int NOT NULL DEFAULT '0' COMMENT '重试次数',
    `start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
    `cost_millis` bigint DEFAULT '0' COMMENT '耗时毫秒',
    `error_code` varchar(64) DEFAULT NULL COMMENT '错误码',
    `error_msg` varchar(1000) DEFAULT NULL COMMENT '错误信息',
    `ext_json` text COMMENT '扩展信息JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_document_task` (`document_id`, `task_type`),
    KEY `idx_task_status` (`task_status`),
    KEY `idx_plan_id` (`plan_id`),
    KEY `idx_source_parse_task_id` (`source_parse_task_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档任务表';


CREATE TABLE IF NOT EXISTS `smartledge_document_task_log` (
                                                               `id` bigint NOT NULL COMMENT '主键id',
                                                               `task_id` bigint NOT NULL COMMENT '任务id',
                                                               `document_id` bigint NOT NULL COMMENT '文档id',
                                                               `stage_type` tinyint NOT NULL COMMENT '阶段类型 1:文件上传 2:内容解析 3:策略路由 4:策略确认 5:切块执行 6:切块后处理 7:向量化 8:入库完成',
                                                               `event_type` tinyint NOT NULL COMMENT '事件类型 1:开始 2:完成 3:失败 4:推荐策略 5:用户调整 6:用户确认',
                                                               `log_level` tinyint NOT NULL DEFAULT '1' COMMENT '日志级别 1:INFO 2:WARN 3:ERROR',
                                                               `operator_type` tinyint NOT NULL DEFAULT '1' COMMENT '操作人类型 1:系统 2:用户 3:管理员',
                                                               `operator_id` bigint DEFAULT NULL COMMENT '操作人id',
                                                               `content` varchar(1000) DEFAULT NULL COMMENT '日志内容',
    `detail_json` text COMMENT '日志明细JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_task_id` (`task_id`),
    KEY `idx_document_id` (`document_id`),
    KEY `idx_stage_type` (`stage_type`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档任务日志表';

CREATE TABLE IF NOT EXISTS `smartledge_document_parse_artifact` (
                                                                     `id` bigint NOT NULL COMMENT '主键id',
                                                                     `document_id` bigint NOT NULL COMMENT '文档id',
                                                                     `task_id` bigint NOT NULL COMMENT '解析任务id',
                                                                     `artifact_type` varchar(32) NOT NULL COMMENT '产物类型 MARKDOWN/JSON/PAGE_IMAGE/TABLE_IMAGE/OCR_JSON',
    `object_name` varchar(512) NOT NULL COMMENT 'MinIO对象名称',
    `content_hash` varchar(128) DEFAULT NULL COMMENT '内容hash',
    `parser_name` varchar(128) DEFAULT NULL COMMENT '解析器名称',
    `parser_version` varchar(64) DEFAULT NULL COMMENT '解析器版本',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_document_task` (`document_id`, `task_id`),
    KEY `idx_task_artifact_type` (`task_id`, `artifact_type`),
    KEY `idx_content_hash` (`content_hash`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档解析产物表';

CREATE TABLE IF NOT EXISTS `smartledge_document_block` (
                                                            `id` bigint NOT NULL COMMENT '主键id',
                                                            `document_id` bigint NOT NULL COMMENT '文档id',
                                                            `task_id` bigint NOT NULL COMMENT '解析任务id',
                                                            `block_no` int NOT NULL COMMENT '解析任务内的稳定block序号',
                                                            `block_type` varchar(32) NOT NULL COMMENT 'block类型 TEXT/TITLE/TABLE/IMAGE/FIGURE/FORMULA/CODE/HEADER/FOOTER',
    `parent_block_id` bigint DEFAULT NULL COMMENT '父级document block id',
    `section_path` varchar(1000) DEFAULT NULL COMMENT '章节路径',
    `canonical_path` varchar(1000) DEFAULT NULL COMMENT '稳定结构路径',
    `page_no` int DEFAULT NULL COMMENT '所在页码',
    `page_range` varchar(64) DEFAULT NULL COMMENT '跨页范围',
    `bbox_json` text COMMENT '版面坐标JSON',
    `text` longtext COMMENT 'block文本',
    `content_with_weight` longtext COMMENT '带标题/章节/关键词等权重信息的检索文本',
    `table_html` longtext COMMENT '表格HTML',
    `image_object_name` varchar(512) DEFAULT NULL COMMENT '图片对象名称',
    `image_caption` longtext COMMENT '图片说明/OCR语义文本',
    `metadata_json` text COMMENT '扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_block_no` (`task_id`, `block_no`),
    KEY `idx_document_task` (`document_id`, `task_id`),
    KEY `idx_task_block_type` (`task_id`, `block_type`),
    KEY `idx_parent_block_id` (`parent_block_id`),
    KEY `idx_page_no` (`page_no`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档解析block表';

CREATE TABLE IF NOT EXISTS `smartledge_document_table` (
                                                            `id` bigint NOT NULL COMMENT '主键id',
                                                            `document_id` bigint NOT NULL COMMENT '文档id',
                                                            `task_id` bigint NOT NULL COMMENT '解析任务id',
                                                            `block_id` bigint NOT NULL COMMENT '来源document block id',
                                                            `table_no` int NOT NULL COMMENT '解析任务内的表格序号',
                                                            `section_path` varchar(1000) DEFAULT NULL COMMENT '章节路径',
    `page_no` int DEFAULT NULL COMMENT '所在页码',
    `page_range` varchar(64) DEFAULT NULL COMMENT '跨页范围',
    `bbox_json` text COMMENT '版面坐标JSON',
    `title` varchar(1000) DEFAULT NULL COMMENT '表格标题',
    `row_count` int NOT NULL DEFAULT '0' COMMENT '数据行数，不含表头',
    `column_count` int NOT NULL DEFAULT '0' COMMENT '列数',
    `table_html` longtext COMMENT '表格HTML',
    `metadata_json` text COMMENT '扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_table_no` (`task_id`, `table_no`),
    KEY `idx_document_task` (`document_id`, `task_id`),
    KEY `idx_task_table_no` (`task_id`, `table_no`),
    KEY `idx_block_id` (`block_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档结构化表格主表';

CREATE TABLE IF NOT EXISTS `smartledge_document_table_column` (
                                                                   `id` bigint NOT NULL COMMENT '主键id',
                                                                   `document_id` bigint NOT NULL COMMENT '文档id',
                                                                   `task_id` bigint NOT NULL COMMENT '解析任务id',
                                                                   `table_id` bigint NOT NULL COMMENT '表格id',
                                                                   `column_no` int NOT NULL COMMENT '列序号，从1开始',
                                                                   `column_name` varchar(500) NOT NULL COMMENT '列名',
    `normalized_name` varchar(500) NOT NULL COMMENT '归一化列名',
    `value_type` varchar(32) NOT NULL COMMENT '值类型 TEXT/NUMBER',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_table_column_no` (`table_id`, `column_no`),
    KEY `idx_document_task` (`document_id`, `task_id`),
    KEY `idx_table_normalized_name` (`table_id`, `normalized_name`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档结构化表格列';

CREATE TABLE IF NOT EXISTS `smartledge_document_table_row` (
                                                                `id` bigint NOT NULL COMMENT '主键id',
                                                                `document_id` bigint NOT NULL COMMENT '文档id',
                                                                `task_id` bigint NOT NULL COMMENT '解析任务id',
                                                                `table_id` bigint NOT NULL COMMENT '表格id',
                                                                `row_no` int NOT NULL COMMENT '数据行序号，从1开始',
                                                                `row_text` longtext COMMENT '行文本快照',
                                                                `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                                                `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
                                                                `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_table_row_no` (`table_id`, `row_no`),
    KEY `idx_document_task` (`document_id`, `task_id`),
    KEY `idx_table_id` (`table_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档结构化表格行';

CREATE TABLE IF NOT EXISTS `smartledge_document_table_cell` (
                                                                 `id` bigint NOT NULL COMMENT '主键id',
                                                                 `document_id` bigint NOT NULL COMMENT '文档id',
                                                                 `task_id` bigint NOT NULL COMMENT '解析任务id',
                                                                 `table_id` bigint NOT NULL COMMENT '表格id',
                                                                 `row_id` bigint NOT NULL COMMENT '行id',
                                                                 `column_id` bigint NOT NULL COMMENT '列id',
                                                                 `row_no` int NOT NULL COMMENT '数据行序号，从1开始',
                                                                 `column_no` int NOT NULL COMMENT '列序号，从1开始',
                                                                 `cell_text` longtext COMMENT '单元格文本',
                                                                 `numeric_value` decimal(30,10) DEFAULT NULL COMMENT '可解析的数值',
    `source_row_no` int DEFAULT NULL COMMENT '原始表格行号，含表头和解析器来源坐标',
    `source_column_no` int DEFAULT NULL COMMENT '原始表格列号，含解析器来源坐标',
    `source_cell_ref` varchar(128) DEFAULT NULL COMMENT '原始单元格引用，例如 Excel A2 或 PDF R2C1',
    `bbox_json` text COMMENT '单元格版面坐标JSON',
    `metadata_json` text COMMENT '单元格扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_table_row_column` (`table_id`, `row_no`, `column_no`),
    KEY `idx_document_task` (`document_id`, `task_id`),
    KEY `idx_table_id` (`table_id`),
    KEY `idx_table_row_no` (`table_id`, `row_no`),
    KEY `idx_table_column_no` (`table_id`, `column_no`),
    KEY `idx_row_id` (`row_id`),
    KEY `idx_column_id` (`column_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档结构化表格单元格';

CREATE TABLE IF NOT EXISTS `smartledge_document_structure_node` (
                                                                     `id` bigint NOT NULL COMMENT '主键id',
                                                                     `document_id` bigint NOT NULL COMMENT '文档id',
                                                                     `parse_task_id` bigint NOT NULL COMMENT '解析任务id',
                                                                     `node_no` int NOT NULL COMMENT '当前文档内的稳定顺序号',
                                                                     `node_type` tinyint NOT NULL COMMENT '节点类型 1:文档根节点 2:章节节点 3:步骤节点 4:列表项节点',
                                                                     `parent_node_id` bigint DEFAULT NULL COMMENT '父节点id',
                                                                     `prev_sibling_node_id` bigint DEFAULT NULL COMMENT '上一个同级节点id',
                                                                     `next_sibling_node_id` bigint DEFAULT NULL COMMENT '下一个同级节点id',
                                                                     `depth` int NOT NULL DEFAULT '0' COMMENT '节点深度',
                                                                     `node_code` varchar(128) DEFAULT NULL COMMENT '节点编码，例如 1.2 / 第一章 / 4',
    `title` varchar(1000) DEFAULT NULL COMMENT '节点标题',
    `anchor_text` varchar(1000) DEFAULT NULL COMMENT '供导航和锚点使用的短锚文本',
    `canonical_path` varchar(1000) DEFAULT NULL COMMENT '节点稳定路径',
    `section_path` varchar(1000) DEFAULT NULL COMMENT '兼容现有系统的章节路径文本',
    `content_text` longtext COMMENT '节点正文',
    `item_index` int DEFAULT NULL COMMENT '列表项/步骤项序号',
    `syntax_schema_version` varchar(64) DEFAULT NULL COMMENT '投影来源的 Markdown 语法契约版本',
    `syntax_source_sha256` char(64) DEFAULT NULL COMMENT '投影来源的 Markdown UTF-8 源文哈希',
    `syntax_node_id` varchar(128) DEFAULT NULL COMMENT '投影来源 syntax node id',
    `syntax_node_type` varchar(32) DEFAULT NULL COMMENT '投影来源 syntax node type',
    `syntax_source_origin` varchar(32) DEFAULT NULL COMMENT '投影来源 SOURCE_MARKDOWN/PROVIDER_MARKDOWN',
    `source_start_byte` int DEFAULT NULL COMMENT 'UTF-8 0-based 半开区间起始 byte',
    `source_end_byte` int DEFAULT NULL COMMENT 'UTF-8 0-based 半开区间结束 byte',
    `source_start_line` int DEFAULT NULL COMMENT '1-based 起始行',
    `source_start_column` int DEFAULT NULL COMMENT '1-based Unicode code-point 起始列',
    `source_end_line` int DEFAULT NULL COMMENT '1-based 半开结束行',
    `source_end_column` int DEFAULT NULL COMMENT '1-based Unicode code-point 半开结束列',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_parse_task_node_no` (`parse_task_id`, `node_no`),
    UNIQUE KEY `uk_parse_task_syntax_node` (`parse_task_id`, `syntax_node_id`),
    KEY `idx_document_id` (`document_id`),
    KEY `idx_parse_task_id` (`parse_task_id`),
    KEY `idx_parent_node_id` (`parent_node_id`),
    KEY `idx_node_type` (`node_type`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档结构节点表';

CREATE TABLE IF NOT EXISTS `smartledge_document_parent_block` (
                                                                   `id` bigint NOT NULL COMMENT '主键id',
                                                                   `document_id` bigint NOT NULL COMMENT '文档id',
                                                                   `task_id` bigint NOT NULL COMMENT '索引任务id',
                                                                   `plan_id` bigint DEFAULT NULL COMMENT '策略方案id',
                                                                   `parent_no` int NOT NULL COMMENT '父块序号',
                                                                   `source_type` tinyint NOT NULL DEFAULT '1' COMMENT '内容来源 1:原文切块 2:后处理补全文本',
                                                                   `section_path` varchar(1000) DEFAULT NULL COMMENT '章节路径',
    `structure_node_id` bigint DEFAULT NULL COMMENT '关联的结构节点id',
    `structure_node_type` tinyint DEFAULT NULL COMMENT '关联的结构节点类型',
    `canonical_path` varchar(1000) DEFAULT NULL COMMENT '结构节点稳定路径',
    `item_index` int DEFAULT NULL COMMENT '列表项/步骤项序号',
    `parent_text` longtext COMMENT '父块完整内容',
    `char_count` int DEFAULT '0' COMMENT '字符数',
    `token_count` int DEFAULT '0' COMMENT 'token数',
    `child_count` int DEFAULT '0' COMMENT '父块内部child数量',
    `start_chunk_no` int DEFAULT NULL COMMENT '父块映射到的第一个child序号',
    `end_chunk_no` int DEFAULT NULL COMMENT '父块映射到的最后一个child序号',
    `page_range` varchar(64) DEFAULT NULL COMMENT '父块覆盖页码范围',
    `source_block_ids` text COMMENT '父块来源document_block id列表JSON',
    `source_provenance_json` longtext COMMENT '父块来源画像/逻辑单元/原文span JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_parent_no` (`task_id`, `parent_no`),
    KEY `idx_document_id` (`document_id`),
    KEY `idx_task_id` (`task_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档父块表';


CREATE TABLE IF NOT EXISTS `smartledge_document_chunk` (
                                                            `id` bigint NOT NULL COMMENT '主键id',
                                                            `document_id` bigint NOT NULL COMMENT '文档id',
                                                            `task_id` bigint NOT NULL COMMENT '索引任务id',
                                                            `plan_id` bigint DEFAULT NULL COMMENT '策略方案id',
                                                            `parent_block_id` bigint NOT NULL COMMENT '所属父块id',
                                                            `chunk_no` int NOT NULL COMMENT '块序号',
                                                            `source_type` tinyint NOT NULL DEFAULT '1' COMMENT '内容来源 1:原文切块 2:后处理补全文本 3:GraphRAG派生证据',
                                                            `section_path` varchar(1000) DEFAULT NULL COMMENT '章节路径',
    `structure_node_id` bigint DEFAULT NULL COMMENT '关联的结构节点id',
    `structure_node_type` tinyint DEFAULT NULL COMMENT '关联的结构节点类型',
    `canonical_path` varchar(1000) DEFAULT NULL COMMENT '结构节点稳定路径',
    `item_index` int DEFAULT NULL COMMENT '列表项/步骤项序号',
    `chunk_text` longtext COMMENT '切块内容',
    `content_with_weight` longtext COMMENT '带标题/章节/关键词/问题等权重信息的检索文本',
    `chunk_type` varchar(32) DEFAULT NULL COMMENT 'chunk类型 TEXT/TITLE/TABLE/IMAGE/FIGURE/CODE/FORMULA/MIXED/GRAPH_ENTITY/GRAPH_RELATION/GRAPH_COMMUNITY',
    `title` varchar(1000) DEFAULT NULL COMMENT 'chunk所属标题或章节标题',
    `keywords` text COMMENT 'chunk关键词 JSON 数组',
    `questions` text COMMENT 'chunk典型问题 JSON 数组',
    `char_count` int DEFAULT '0' COMMENT '字符数',
    `token_count` int DEFAULT '0' COMMENT 'token数',
    `vector_status` tinyint NOT NULL DEFAULT '1' COMMENT '向量状态 1:待向量化 2:向量化中 3:向量化成功 4:向量化失败',
    `vector_store_type` tinyint NOT NULL DEFAULT '1' COMMENT '向量库类型 1:Milvus 2:PGVector 3:Elasticsearch',
    `vector_id` varchar(128) DEFAULT NULL COMMENT '向量库主键',
    `page_no` int DEFAULT NULL COMMENT '命中块所在页码',
    `page_range` varchar(64) DEFAULT NULL COMMENT '命中块覆盖页码范围',
    `bbox_json` text COMMENT '命中块版面坐标JSON',
    `source_block_ids` text COMMENT 'chunk来源document_block id列表JSON',
    `source_provenance_json` longtext COMMENT 'chunk来源画像/逻辑单元/原文span JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_chunk_no` (`task_id`, `chunk_no`),
    KEY `idx_document_id` (`document_id`),
    KEY `idx_parent_block_id` (`parent_block_id`),
    KEY `idx_chunk_type` (`chunk_type`),
    KEY `idx_vector_status` (`vector_status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档切块表';


CREATE TABLE IF NOT EXISTS `smartledge_kg_entity` (
                                                       `id` bigint NOT NULL COMMENT '主键id',
                                                       `document_id` bigint NOT NULL COMMENT '文档id',
                                                       `task_id` bigint NOT NULL COMMENT '索引任务id',
                                                       `entity_key` varchar(255) NOT NULL COMMENT '实体稳定键，来自抽取工具的实体id',
    `name` varchar(500) NOT NULL COMMENT '实体名称',
    `normalized_name` varchar(500) DEFAULT NULL COMMENT '实体归一化名称',
    `entity_type` varchar(64) NOT NULL DEFAULT 'CONCEPT' COMMENT '实体类型 CONCEPT/SECTION/SYSTEM/ORG/PROCESS/METRIC 等',
    `description` varchar(1000) DEFAULT NULL COMMENT '实体描述',
    `metadata_json` text COMMENT '实体扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kg_entity_task_key` (`task_id`, `entity_key`),
    KEY `idx_kg_entity_document_task` (`document_id`, `task_id`),
    KEY `idx_kg_entity_normalized` (`document_id`, `normalized_name`),
    KEY `idx_kg_entity_type` (`document_id`, `entity_type`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG实体表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_relation` (
                                                         `id` bigint NOT NULL COMMENT '主键id',
                                                         `document_id` bigint NOT NULL COMMENT '文档id',
                                                         `task_id` bigint NOT NULL COMMENT '索引任务id',
                                                         `source_entity_id` bigint NOT NULL COMMENT '起点实体id',
                                                         `target_entity_id` bigint NOT NULL COMMENT '终点实体id',
                                                         `relation_type` varchar(64) NOT NULL DEFAULT 'ASSOCIATED_WITH' COMMENT '关系类型',
    `description` varchar(1000) DEFAULT NULL COMMENT '关系描述',
    `weight` decimal(10,4) NOT NULL DEFAULT '1.0000' COMMENT '关系权重',
    `metadata_json` text COMMENT '关系扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_kg_relation_document_task` (`document_id`, `task_id`),
    KEY `idx_kg_relation_source` (`source_entity_id`),
    KEY `idx_kg_relation_target` (`target_entity_id`),
    KEY `idx_kg_relation_type` (`document_id`, `relation_type`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG实体关系表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_evidence` (
                                                         `id` bigint NOT NULL COMMENT '主键id',
                                                         `document_id` bigint NOT NULL COMMENT '文档id',
                                                         `task_id` bigint NOT NULL COMMENT '索引任务id',
                                                         `entity_id` bigint DEFAULT NULL COMMENT '被支撑的实体id',
                                                         `relation_id` bigint DEFAULT NULL COMMENT '被支撑的关系id',
                                                         `chunk_id` bigint DEFAULT NULL COMMENT '来源chunk id',
                                                         `parent_block_id` bigint DEFAULT NULL COMMENT '来源父块id',
                                                         `quote_text` longtext COMMENT '证据原文片段',
                                                         `page_no` int DEFAULT NULL COMMENT '证据所在页码',
                                                         `page_range` varchar(64) DEFAULT NULL COMMENT '证据跨页范围',
    `bbox_json` text COMMENT '证据版面坐标JSON',
    `section_path` varchar(1000) DEFAULT NULL COMMENT '证据章节路径',
    `metadata_json` text COMMENT '证据扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_kg_evidence_document_task` (`document_id`, `task_id`),
    KEY `idx_kg_evidence_entity` (`entity_id`),
    KEY `idx_kg_evidence_relation` (`relation_id`),
    KEY `idx_kg_evidence_chunk` (`chunk_id`),
    KEY `idx_kg_evidence_parent_block` (`parent_block_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG证据表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_canonical_entity_group` (
                                                                       `id` bigint NOT NULL COMMENT '主键id',
                                                                       `scope_key` varchar(255) NOT NULL COMMENT '跨文档图谱派生索引范围，默认 knowledge_scope 或 global',
    `group_key` varchar(255) NOT NULL COMMENT 'canonical实体组稳定键',
    `canonical_name` varchar(500) NOT NULL COMMENT 'canonical实体名称',
    `entity_type` varchar(64) NOT NULL DEFAULT 'CONCEPT' COMMENT '实体类型',
    `entity_count` int NOT NULL DEFAULT '0' COMMENT '组内实体数',
    `document_count` int NOT NULL DEFAULT '0' COMMENT '覆盖文档数',
    `task_count` int NOT NULL DEFAULT '0' COMMENT '覆盖任务数',
    `rank_score` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '跨文档图谱全局rank分',
    `metadata_json` text COMMENT '派生索引扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kg_canonical_scope_group` (`scope_key`, `group_key`),
    KEY `idx_kg_canonical_scope_name` (`scope_key`, `canonical_name`),
    KEY `idx_kg_canonical_scope_type` (`scope_key`, `entity_type`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG跨文档canonical实体组派生表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_canonical_entity_member` (
                                                                        `id` bigint NOT NULL COMMENT '主键id',
                                                                        `scope_key` varchar(255) NOT NULL COMMENT '跨文档图谱派生索引范围',
    `group_id` bigint NOT NULL COMMENT 'canonical实体组id',
    `group_key` varchar(255) NOT NULL COMMENT 'canonical实体组稳定键',
    `entity_id` bigint NOT NULL COMMENT 'KG实体id',
    `document_id` bigint NOT NULL COMMENT '文档id',
    `task_id` bigint NOT NULL COMMENT '索引任务id',
    `entity_name` varchar(500) NOT NULL COMMENT '实体名称',
    `normalized_name` varchar(500) DEFAULT NULL COMMENT '实体归一化名称',
    `entity_type` varchar(64) NOT NULL DEFAULT 'CONCEPT' COMMENT '实体类型',
    `metadata_json` text COMMENT '派生索引成员扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kg_canonical_member_entity` (`scope_key`, `entity_id`),
    KEY `idx_kg_canonical_member_group` (`scope_key`, `group_id`),
    KEY `idx_kg_canonical_member_document` (`document_id`, `task_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG跨文档canonical实体成员派生表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_relation_group` (
                                                               `id` bigint NOT NULL COMMENT '主键id',
                                                               `scope_key` varchar(255) NOT NULL COMMENT '跨文档图谱派生索引范围',
    `group_key` varchar(255) NOT NULL COMMENT 'relation group持久化稳定键，长自然key保存在metadata_json',
    `source_group_key` varchar(255) NOT NULL COMMENT '起点canonical实体组key',
    `target_group_key` varchar(255) NOT NULL COMMENT '终点canonical实体组key',
    `relation_type` varchar(64) NOT NULL DEFAULT 'ASSOCIATED_WITH' COMMENT '关系类型',
    `relation_count` int NOT NULL DEFAULT '0' COMMENT '组内关系数',
    `evidence_count` int NOT NULL DEFAULT '0' COMMENT '组内证据数',
    `document_count` int NOT NULL DEFAULT '0' COMMENT '覆盖文档数',
    `rank_score` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '跨文档关系组rank分',
    `metadata_json` text COMMENT '派生索引扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kg_relation_group_scope_key` (`scope_key`, `group_key`),
    KEY `idx_kg_relation_group_source` (`scope_key`, `source_group_key`),
    KEY `idx_kg_relation_group_target` (`scope_key`, `target_group_key`),
    KEY `idx_kg_relation_group_type` (`scope_key`, `relation_type`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG跨文档relation group派生表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_relation_group_member` (
                                                                      `id` bigint NOT NULL COMMENT '主键id',
                                                                      `scope_key` varchar(255) NOT NULL COMMENT '跨文档图谱派生索引范围',
    `group_id` bigint NOT NULL COMMENT 'relation group id',
    `group_key` varchar(255) NOT NULL COMMENT 'relation group持久化稳定键，长自然key保存在metadata_json',
    `relation_id` bigint NOT NULL COMMENT 'KG关系id',
    `document_id` bigint NOT NULL COMMENT '文档id',
    `task_id` bigint NOT NULL COMMENT '索引任务id',
    `evidence_count` int NOT NULL DEFAULT '0' COMMENT '该关系证据数',
    `metadata_json` text COMMENT '派生索引成员扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kg_relation_group_member_relation` (`scope_key`, `relation_id`),
    KEY `idx_kg_relation_group_member_group` (`scope_key`, `group_id`),
    KEY `idx_kg_relation_group_member_document` (`document_id`, `task_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG跨文档relation group成员派生表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_cross_document_community` (
                                                                         `id` bigint NOT NULL COMMENT '主键id',
                                                                         `scope_key` varchar(255) NOT NULL COMMENT '跨文档图谱派生索引范围',
    `community_key` varchar(255) NOT NULL COMMENT '跨文档community稳定键',
    `title` varchar(500) NOT NULL COMMENT '跨文档community标题',
    `summary` longtext COMMENT '跨文档community摘要',
    `canonical_group_keys_json` text COMMENT 'community包含的canonical实体组key JSON数组',
    `relation_group_keys_json` text COMMENT 'community包含的relation group key JSON数组',
    `entity_count` int NOT NULL DEFAULT '0' COMMENT '覆盖canonical实体组数',
    `relation_group_count` int NOT NULL DEFAULT '0' COMMENT '覆盖relation group数',
    `evidence_count` int NOT NULL DEFAULT '0' COMMENT '覆盖证据数',
    `document_count` int NOT NULL DEFAULT '0' COMMENT '覆盖文档数',
    `rank_score` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '跨文档community rank分',
    `metadata_json` text COMMENT '派生索引扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kg_xdoc_community_scope_key` (`scope_key`, `community_key`),
    KEY `idx_kg_xdoc_community_scope_rank` (`scope_key`, `rank_score`),
    KEY `idx_kg_xdoc_community_scope_docs` (`scope_key`, `document_count`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG跨文档community派生表';

CREATE TABLE IF NOT EXISTS `smartledge_kg_cross_document_community_member` (
                                                                                `id` bigint NOT NULL COMMENT '主键id',
                                                                                `scope_key` varchar(255) NOT NULL COMMENT '跨文档图谱派生索引范围',
    `community_id` bigint NOT NULL COMMENT '跨文档community id',
    `community_key` varchar(255) NOT NULL COMMENT '跨文档community稳定键',
    `relation_group_id` bigint NOT NULL COMMENT 'relation group id',
    `relation_group_key` varchar(255) NOT NULL COMMENT 'relation group持久化稳定键',
    `source_group_key` varchar(255) NOT NULL COMMENT '起点canonical实体组key',
    `target_group_key` varchar(255) NOT NULL COMMENT '终点canonical实体组key',
    `relation_type` varchar(64) NOT NULL DEFAULT 'ASSOCIATED_WITH' COMMENT '关系类型',
    `relation_count` int NOT NULL DEFAULT '0' COMMENT '组内关系数',
    `evidence_count` int NOT NULL DEFAULT '0' COMMENT '组内证据数',
    `document_count` int NOT NULL DEFAULT '0' COMMENT '覆盖文档数',
    `metadata_json` text COMMENT '派生索引成员扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kg_xdoc_community_member_group` (`scope_key`, `relation_group_id`),
    KEY `idx_kg_xdoc_community_member_community` (`scope_key`, `community_id`),
    KEY `idx_kg_xdoc_community_member_relation` (`scope_key`, `relation_group_key`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='GraphRAG跨文档community成员派生表';

CREATE TABLE IF NOT EXISTS `smartledge_raptor_node` (
                                                         `id` bigint NOT NULL COMMENT '主键id',
                                                         `document_id` bigint NOT NULL COMMENT '文档id',
                                                         `task_id` bigint NOT NULL COMMENT '索引任务id',
                                                         `scope_type` varchar(32) NOT NULL DEFAULT 'DOCUMENT' COMMENT 'RAPTOR摘要范围类型：DOCUMENT/DATASET',
    `scope_key` varchar(255) NOT NULL DEFAULT '' COMMENT 'RAPTOR摘要范围键，例如 document:{id} / knowledge:{code} / global',
    `node_key` varchar(255) NOT NULL COMMENT 'RAPTOR工具返回的节点稳定键',
    `parent_node_id` bigint DEFAULT NULL COMMENT '父摘要节点id',
    `node_level` int NOT NULL COMMENT '摘要树层级，1为最贴近原文的摘要',
    `node_no` int NOT NULL COMMENT '同层节点序号',
    `title` varchar(500) DEFAULT NULL COMMENT '摘要节点标题',
    `summary` longtext COMMENT '摘要文本',
    `summary_with_weight` longtext COMMENT '带标题、章节、关键词、问题的加权检索文本',
    `child_node_ids_json` text COMMENT '子摘要节点id JSON数组',
    `source_chunk_ids_json` text COMMENT '可下钻的原文chunk id JSON数组',
    `source_parent_block_ids_json` text COMMENT '可下钻的父块id JSON数组',
    `source_document_ids_json` text COMMENT '跨文档摘要覆盖的文档id JSON数组',
    `source_task_ids_json` text COMMENT '跨文档摘要覆盖的索引任务id JSON数组',
    `section_path` varchar(1000) DEFAULT NULL COMMENT '摘要覆盖章节路径',
    `page_range` varchar(64) DEFAULT NULL COMMENT '摘要覆盖页码范围',
    `keywords` text COMMENT '摘要关键词 JSON数组',
    `questions` text COMMENT '摘要典型问题 JSON数组',
    `metadata_json` text COMMENT '摘要节点扩展元数据JSON',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_raptor_node_task_key` (`task_id`, `node_key`),
    KEY `idx_raptor_node_scope` (`scope_type`, `scope_key`),
    KEY `idx_raptor_node_document_task` (`document_id`, `task_id`),
    KEY `idx_raptor_node_parent` (`parent_node_id`),
    KEY `idx_raptor_node_level` (`document_id`, `node_level`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='RAPTOR层级摘要节点表';


CREATE TABLE IF NOT EXISTS `smartledge_knowledge_scope_node` (
                                                                  `id` bigint NOT NULL COMMENT '主键id',
                                                                  `knowledge_base_id` bigint NOT NULL COMMENT '所属知识库id',
                                                                  `scope_name` varchar(128) NOT NULL COMMENT '知识范围名称',
    `parent_scope_id` bigint DEFAULT NULL COMMENT '父级知识范围id',
    `description` varchar(1024) DEFAULT NULL COMMENT '范围描述',
    `aliases` varchar(512) DEFAULT NULL COMMENT '别名，英文逗号分隔',
    `examples` text COMMENT '典型问题 JSON 数组',
    `sort_order` int DEFAULT '0' COMMENT '排序值',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_knowledge_base_id` (`knowledge_base_id`),
    KEY `idx_parent_scope_id` (`parent_scope_id`),
    KEY `idx_status` (`status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识范围节点表';


CREATE TABLE IF NOT EXISTS `smartledge_knowledge_topic_node` (
                                                                  `id` bigint NOT NULL COMMENT '主键id',
                                                                  `knowledge_base_id` bigint NOT NULL COMMENT '所属知识库id',
                                                                  `topic_name` varchar(128) NOT NULL COMMENT '主题名称',
    `scope_id` bigint NOT NULL COMMENT '所属知识范围id',
    `description` varchar(1024) DEFAULT NULL COMMENT '主题描述',
    `aliases` varchar(512) DEFAULT NULL COMMENT '别名，英文逗号分隔',
    `examples` text COMMENT '典型问题 JSON 数组',
    `answer_shape` varchar(64) DEFAULT NULL COMMENT '建议回答形态 explain/list/steps/compare/structure',
    `execution_preference` varchar(64) DEFAULT NULL COMMENT '执行偏好 retrieval/graph_only/graph_then_evidence/graph_assist',
    `sort_order` int DEFAULT '0' COMMENT '排序值',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_knowledge_base_id` (`knowledge_base_id`),
    KEY `idx_scope_id` (`scope_id`),
    KEY `idx_status` (`status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识主题节点表';


CREATE TABLE IF NOT EXISTS `smartledge_document_profile` (
                                                              `id` bigint NOT NULL COMMENT '主键id',
                                                              `document_id` bigint NOT NULL COMMENT '文档id',
                                                              `profile_version` int DEFAULT '1' COMMENT '画像版本',
                                                              `document_summary` text COMMENT '文档摘要',
                                                              `document_type` varchar(64) DEFAULT NULL COMMENT '文档类型；auto 使用 plain_text/structured_section/structured_outline/structured_items，manual 可配置',
    `core_topics` text COMMENT '核心主题 JSON 数组',
    `example_questions` text COMMENT '典型问题 JSON 数组',
    `graph_friendly` tinyint(1) DEFAULT '0' COMMENT '是否适合图结构问答 1:是 0:否',
    `supports_graph_outline` tinyint(1) DEFAULT '0' COMMENT '是否支持章节列表/目录类图回答',
    `supports_item_lookup` tinyint(1) DEFAULT '0' COMMENT '是否支持步骤/item 查询',
    `supports_graph_assist` tinyint(1) DEFAULT '0' COMMENT '是否支持图辅助检索',
    `profile_source` varchar(64) DEFAULT NULL COMMENT '画像来源 auto/manual/mixed',
    `profile_status` tinyint DEFAULT '1' COMMENT '画像状态 1:待生成 2:生成成功 3:生成失败 4:人工确认',
    `error_msg` varchar(1024) DEFAULT NULL COMMENT '画像失败原因',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_document_id` (`document_id`),
    KEY `idx_profile_status` (`profile_status`),
    KEY `idx_document_type` (`document_type`),
    KEY `idx_status` (`status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档画像表';


CREATE TABLE IF NOT EXISTS `smartledge_topic_document_relation` (
                                                                     `id` bigint NOT NULL COMMENT '主键id',
                                                                     `knowledge_base_id` bigint NOT NULL COMMENT '所属知识库id',
                                                                     `topic_id` bigint NOT NULL COMMENT '主题id',
                                                                     `document_id` bigint NOT NULL COMMENT '文档id',
                                                                     `relation_score` decimal(8,4) DEFAULT '0.0000' COMMENT '关联分数',
    `relation_source` varchar(64) DEFAULT NULL COMMENT '关联来源 auto/manual/mixed',
    `reason` varchar(1024) DEFAULT NULL COMMENT '关联原因',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_base_topic_document` (`knowledge_base_id`, `topic_id`, `document_id`),
    KEY `idx_knowledge_base_id` (`knowledge_base_id`),
    KEY `idx_document_id` (`document_id`),
    KEY `idx_topic_id` (`topic_id`),
    KEY `idx_status` (`status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='主题文档关联表';


CREATE TABLE IF NOT EXISTS `smartledge_knowledge_route_trace` (
                                                                   `id` bigint NOT NULL COMMENT '主键id',
                                                                   `conversation_id` varchar(64) DEFAULT NULL COMMENT '会话id',
    `exchange_id` bigint DEFAULT NULL COMMENT '轮次id',
    `question` text COMMENT '原始问题',
    `rewrite_question` text COMMENT '改写问题',
    `mode` varchar(32) DEFAULT NULL COMMENT '运行模式 shadow/auto',
    `knowledge_base_selection_mode` varchar(16) DEFAULT NULL COMMENT '知识库选择模式 NONE/ALL/SELECTED',
    `selected_knowledge_base_ids_json` JSON DEFAULT NULL COMMENT '已选知识库id快照',
    `selected_knowledge_base_names_json` JSON DEFAULT NULL COMMENT '已选知识库名称快照',
    `allowed_document_ids_json` JSON DEFAULT NULL COMMENT '知识库硬边界允许检索的文档id快照',
    `top_scopes_json` text COMMENT '候选知识范围 JSON',
    `top_topics_json` text COMMENT '候选主题 JSON',
    `top_documents_json` text COMMENT '候选文档 JSON',
    `selected_document_id` bigint DEFAULT NULL COMMENT '当前实际使用文档id',
    `hit_selected_document` tinyint(1) DEFAULT NULL COMMENT '候选是否命中实际文档',
    `confidence` decimal(8,4) DEFAULT '0.0000' COMMENT '整体置信度',
    `route_status` tinyint DEFAULT '1' COMMENT '路由状态 1:成功 2:低置信 3:失败',
    `error_msg` varchar(1024) DEFAULT NULL COMMENT '失败原因',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
    `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (`id`),
    KEY `idx_conversation_exchange` (`conversation_id`, `exchange_id`),
    KEY `idx_selected_document_id` (`selected_document_id`),
    KEY `idx_route_status` (`route_status`),
    KEY `idx_create_time` (`create_time`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识路由影子追踪表';


CREATE TABLE IF NOT EXISTS smartledge_chat_retrieval_result (
                                                                 id BIGINT NOT NULL COMMENT '主键id',
                                                                 dialogue_code VARCHAR(64) NOT NULL COMMENT '所属业务会话编号',
    exchange_id BIGINT NOT NULL COMMENT '所属轮次id',
    trace_id VARCHAR(64) NOT NULL COMMENT '本轮执行trace id',
    sub_question_index INT NOT NULL DEFAULT '1' COMMENT '子问题下标（从1开始）',
    sub_question TEXT DEFAULT NULL COMMENT '子问题文本',
    candidate_id VARCHAR(255) DEFAULT NULL COMMENT 'O9稳定候选身份：citation身份优先，其次context身份，最后docId，用于跨阶段追踪',
    channel_type VARCHAR(32) NOT NULL COMMENT '检索通道：vector/keyword/hybrid',
    channel_rank INT DEFAULT NULL COMMENT '通道内原始排名',
    rrf_rank INT DEFAULT NULL COMMENT 'RRF融合后排名',
    final_rank INT DEFAULT NULL COMMENT '最终排名（rerank后或最终裁剪后）',
    original_score DECIMAL(12, 6) DEFAULT NULL COMMENT '通道原始分数',
    rrf_score DECIMAL(12, 6) DEFAULT NULL COMMENT 'RRF排名特征分数',
    hybrid_score DECIMAL(12, 6) DEFAULT NULL COMMENT 'weighted hybrid最终融合分数',
    metadata_boost DECIMAL(12, 6) DEFAULT NULL COMMENT '标题/章节/关键词等元数据加分',
    vector_score DECIMAL(12, 6) DEFAULT NULL COMMENT '向量通道原始分数',
    keyword_score DECIMAL(12, 6) DEFAULT NULL COMMENT '关键词通道原始分数',
    rerank_score DECIMAL(12, 6) DEFAULT NULL COMMENT 'Rerank精排分数',
    gate_passed TINYINT(1) DEFAULT '1' COMMENT '是否通过相关性闸门：1是 0否',
    is_elevated TINYINT(1) DEFAULT '0' COMMENT '是否提升到父块：1是 0否',
    is_selected TINYINT(1) DEFAULT '0' COMMENT '是否被选入最终Prompt：1是 0否',
    selection_reason VARCHAR(255) DEFAULT NULL COMMENT '命中候选的选入原因（仅observation，不反向参与业务逻辑）',
    filtered_reason VARCHAR(255) DEFAULT NULL COMMENT '被过滤候选的过滤原因：gate/candidateTopK/rerankTopK/finalTopK（仅observation）',
    rank_feature VARCHAR(1024) DEFAULT NULL COMMENT 'rank feature观测串：metadataBoost/KG质量/pagerank/RAPTOR词面boost等弱排序特征（仅observation）',
    document_id BIGINT DEFAULT NULL COMMENT '文档id',
    document_name VARCHAR(255) DEFAULT NULL COMMENT '文档名称',
    chunk_id BIGINT DEFAULT NULL COMMENT '文档切块id',
    chunk_type VARCHAR(32) DEFAULT NULL COMMENT '切块类型：TEXT/LIST/TABLE/TITLE/RAPTOR_SOURCE_CHUNK等',
    chunk_no INT DEFAULT NULL COMMENT '切块序号',
    parent_block_id BIGINT DEFAULT NULL COMMENT '父块id',
    parent_block_no INT DEFAULT NULL COMMENT '父块序号',
    section_path VARCHAR(512) DEFAULT NULL COMMENT '章节路径',
    chunk_text_preview VARCHAR(500) DEFAULT NULL COMMENT '文档块内容预览（前500字符）',
    chunk_char_count INT DEFAULT NULL COMMENT '文档块字符数',
    context_identity VARCHAR(255) DEFAULT NULL COMMENT '上下文身份：ParentBlock、GraphRAG包装、RAPTOR摘要等',
    citation_identity MEDIUMTEXT DEFAULT NULL COMMENT '真实可引用证据身份：chunk/quote/table cell/source chunk',
    citation_identity_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '完整citation identity的UTF-8 SHA-256定长索引投影',
    citation_evidence_type VARCHAR(64) DEFAULT NULL COMMENT '引用证据类型：CHUNK/TABLE_CELL_OR_ROW/KG_QUOTE_SOURCE/RAPTOR_SOURCE_CHUNK/CONTEXT_ONLY',
    context_only TINYINT(1) DEFAULT '0' COMMENT '是否仅为上下文，不可直接作为citation证据',
    source_evidence_resolved TINYINT(1) DEFAULT '0' COMMENT '是否已解析到真实可引用source evidence',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_retrieval_result_exchange (dialogue_code, exchange_id),
    KEY idx_retrieval_result_trace (trace_id),
    KEY idx_retrieval_result_sub_question (exchange_id, sub_question_index),
    KEY idx_retrieval_result_channel (channel_type, is_selected),
    KEY idx_retrieval_result_document (document_id, chunk_id),
    KEY idx_retrieval_result_exchange_citation_hash (exchange_id, sub_question_index, citation_identity_hash),
    KEY idx_retrieval_result_context_only (context_only, source_evidence_resolved)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检索结果快照表';

CREATE TABLE IF NOT EXISTS smartledge_chat_channel_execution (
                                                                  id BIGINT NOT NULL COMMENT '主键id',
                                                                  dialogue_code VARCHAR(64) NOT NULL COMMENT '所属业务会话编号',
    exchange_id BIGINT NOT NULL COMMENT '所属轮次id',
    trace_id VARCHAR(64) NOT NULL COMMENT '本轮执行trace id',
    sub_question_index INT NOT NULL DEFAULT '1' COMMENT '子问题下标（从1开始）',
    sub_question TEXT DEFAULT NULL COMMENT '子问题文本',
    channel_type VARCHAR(32) NOT NULL COMMENT '检索通道：vector/keyword',
    execution_state TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1:成功 2:失败 3:超时 4:跳过',
    start_time DATETIME(3) DEFAULT NULL COMMENT '通道执行开始时间（毫秒精度）',
    end_time DATETIME(3) DEFAULT NULL COMMENT '通道执行结束时间（毫秒精度）',
    duration_ms BIGINT DEFAULT NULL COMMENT '通道执行耗时，毫秒',
    recalled_count INT DEFAULT '0' COMMENT '原始召回数',
    accepted_count INT DEFAULT '0' COMMENT '闸门后保留数',
    final_selected_count INT DEFAULT '0' COMMENT '最终选入Prompt数',
    avg_score DECIMAL(12, 6) DEFAULT NULL COMMENT '平均分数',
    max_score DECIMAL(12, 6) DEFAULT NULL COMMENT '最高分数',
    min_score DECIMAL(12, 6) DEFAULT NULL COMMENT '最低分数',
    config_snapshot JSON DEFAULT NULL COMMENT '通道配置快照（topK、阈值等）',
    error_message TEXT DEFAULT NULL COMMENT '错误信息',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_channel_exec_exchange (dialogue_code, exchange_id),
    KEY idx_channel_exec_trace (trace_id),
    KEY idx_channel_exec_channel (channel_type, execution_state)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检索通道执行详情表';

CREATE TABLE IF NOT EXISTS smartledge_chat_stage_benchmark (
                                                                id BIGINT NOT NULL COMMENT '主键id',
                                                                stage_code VARCHAR(64) NOT NULL COMMENT '阶段编码',
    execution_mode VARCHAR(32) NOT NULL COMMENT '执行模式：RETRIEVAL/GRAPH_ONLY/GRAPH_THEN_EVIDENCE/REACT_AGENT/CLARIFICATION',
    p50_duration_ms BIGINT DEFAULT NULL COMMENT 'P50耗时（毫秒）',
    p90_duration_ms BIGINT DEFAULT NULL COMMENT 'P90耗时（毫秒）',
    p99_duration_ms BIGINT DEFAULT NULL COMMENT 'P99耗时（毫秒）',
    avg_duration_ms BIGINT DEFAULT NULL COMMENT '平均耗时（毫秒）',
    max_duration_ms BIGINT DEFAULT NULL COMMENT '最大耗时（毫秒）',
    min_duration_ms BIGINT DEFAULT NULL COMMENT '最小耗时（毫秒）',
    sample_count INT DEFAULT '0' COMMENT '样本数量',
    recent_durations JSON DEFAULT NULL COMMENT '最近N次耗时记录（用于滑动窗口计算）',
    last_update_time DATETIME DEFAULT NULL COMMENT '最后更新时间',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_stage_benchmark_code_mode (stage_code, execution_mode)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='阶段性能基准表';

CREATE TABLE IF NOT EXISTS smartledge_system_config (
    id BIGINT NOT NULL COMMENT '固定主键，当前全局配置使用1',
    config_version INT NOT NULL DEFAULT '0' COMMENT '乐观锁配置版本',
    config_json JSON NOT NULL COMMENT '注册表管理的完整内部配置快照，不直接暴露给前端',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统当前配置表';

CREATE TABLE IF NOT EXISTS smartledge_system_config_group (
    id BIGINT NOT NULL COMMENT '主键id',
    group_key VARCHAR(64) NOT NULL COMMENT '总分类稳定标识',
    group_label VARCHAR(64) NOT NULL COMMENT '总分类显示名称',
    group_description VARCHAR(255) NOT NULL COMMENT '总分类说明',
    sort_order INT NOT NULL DEFAULT '0' COMMENT '总分类显示顺序',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_system_config_group_key (group_key),
    KEY idx_system_config_group_sort (status, sort_order, id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置总分类表';

CREATE TABLE IF NOT EXISTS smartledge_system_config_category (
    id BIGINT NOT NULL COMMENT '主键id',
    group_key VARCHAR(64) NOT NULL COMMENT '所属总分类稳定标识',
    category_key VARCHAR(64) NOT NULL COMMENT '小分类稳定标识',
    category_label VARCHAR(64) NOT NULL COMMENT '小分类显示名称',
    category_description VARCHAR(255) NOT NULL COMMENT '小分类说明',
    sort_order INT NOT NULL DEFAULT '0' COMMENT '小分类在总分类内的显示顺序',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_system_config_category_key (category_key),
    KEY idx_system_config_category_group_sort (group_key, status, sort_order, id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置小分类表';

CREATE TABLE IF NOT EXISTS smartledge_system_config_history (
    id BIGINT NOT NULL COMMENT '主键id',
    before_version INT NOT NULL COMMENT '修改前配置版本',
    after_version INT NOT NULL COMMENT '修改后配置版本',
    before_config_json JSON NOT NULL COMMENT '修改前完整内部配置快照',
    after_config_json JSON NOT NULL COMMENT '修改后完整内部配置快照',
    change_note VARCHAR(255) NOT NULL COMMENT '修改或恢复说明',
    operator_name VARCHAR(64) NOT NULL COMMENT '后台操作人',
    source_type VARCHAR(16) NOT NULL COMMENT 'MANUAL/RESTORE/INIT',
    restore_from_history_id BIGINT DEFAULT NULL COMMENT '恢复操作引用的历史记录id',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_system_config_history_version (after_version),
    KEY idx_system_config_history_create_time (create_time),
    KEY idx_system_config_history_restore_source (restore_from_history_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置修改历史表';
